// `npm run build` for the API. The server is plain CommonJS JavaScript, so there
// is nothing to compile. This makes any common host configuration work:
//   Build `npm ci` / `npm install` / `npm run build`  +  Start `npm start` / `node dist/index.js`
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

// A build command of just `npm run build` never installs packages; do it here.
if (!fs.existsSync(path.join(root, 'node_modules', 'express'))) {
  console.log('Installing dependencies (npm ci)…');
  execSync('npm ci', { cwd: root, stdio: 'inherit' });
}

// Entry for hosts configured with `node dist/index.js`. It just runs index.js.
const dist = path.join(root, 'dist');
fs.mkdirSync(dist, { recursive: true });
fs.writeFileSync(
  path.join(dist, 'index.js'),
  "// Generated by `npm run build`. The API has no compile step; this starts ../index.js.\nrequire('../index.js');\n"
);

console.log('Build complete. Start with `npm start` (or `node dist/index.js`).');
